import { Listing } from "../../types/Listing";

export const testData: Listing[] = [
  {
    listing_id: 1,
    title: "Cozy Dorm in the City",
    description:
      "A comfortable dormitory located in the heart of the city. Close to public transportation.",
    location: "123 Main St, City",
    type: "Dormitory",
    capacity: 6,
    price_per_month: 4500,
    minimum_stay: 1,
    rating: 4.5,
    number_of_reviews: 35,
    host_id: 101,
    host_name: "John Doe",
    host_response_rate: "95%",
    host_response_time: "Within an hour",
    amenities: ["Wi-Fi", "Kitchen Access", "Laundry Facilities"],
    availability_calendar: "[Sample calendar data]",
    display_picture: "https://via.placeholder.com/500",
    coordinates: {
      latitude: 14.828576,
      longitude: 120.281357,
    },
  },
  {
    listing_id: 2,
    title: "Private Room Near Campus",
    description:
      "Spacious private room within walking distance to the university campus.",
    location: "456 Elm St, College",
    type: "Private Room",
    capacity: 2,
    price_per_month: 4500,
    minimum_stay: 2,
    rating: 4.8,
    number_of_reviews: 25,
    host_id: 102,
    host_name: "Jane Smith",
    host_response_rate: "100%",
    host_response_time: "Within a few hours",
    amenities: ["Wi-Fi", "Parking"],
    availability_calendar: "[Sample calendar data]",
    display_picture: "https://via.placeholder.com/500",
    coordinates: {
      latitude: 14.829907,
      longitude: 120.282399,
    },
  },
  {
    listing_id: 3,
    title: "Studio Apartment",
    description:
      "Fully furnished studio apartment with a stunning view of the city skyline.",
    location: "789 Oak St, Downtown",
    type: "Entire Place",
    capacity: 2,
    price_per_month: 4500,
    minimum_stay: 3,
    rating: 4.9,
    number_of_reviews: 45,
    host_id: 103,
    host_name: "Emily Brown",
    host_response_rate: "98%",
    host_response_time: "Within a day",
    amenities: ["Wi-Fi", "Gym Access", "Pool"],
    availability_calendar: "[Sample calendar data]",
    display_picture: "https://via.placeholder.com/500",
    coordinates: {
      latitude: 14.831599,
      longitude: 120.282051,
    },
  },
  {
    listing_id: 4,
    title: "Budget Shared Room",
    description:
      "Affordable shared room ideal for budget travelers. Close to restaurants and nightlife.",
    location: "321 Pine St, Downtown",
    type: "Shared Room",
    capacity: 4,
    price_per_month: 4500,
    minimum_stay: 1,
    rating: 4.0,
    number_of_reviews: 12,
    host_id: 104,
    host_name: "Michael Lee",
    host_response_rate: "85%",
    host_response_time: "Within an hour",
    amenities: ["Wi-Fi", "Breakfast"],
    availability_calendar: "[Sample calendar data]",
    display_picture: "https://via.placeholder.com/500",
    coordinates: {
      latitude: 14.828868,
      longitude: 120.27844,
    },
  },
  {
    listing_id: 5,
    title: "Lakeside Cabin Retreat",
    description:
      "Tranquil cabin nestled by the lake, perfect for a weekend getaway.",
    location: "111 Lakeview Dr",
    type: "Entire Place",
    capacity: 4,
    price_per_month: 4500,
    minimum_stay: 2,
    rating: 4.7,
    number_of_reviews: 30,
    host_id: 105,
    host_name: "Sarah Johnson",
    host_response_rate: "97%",
    host_response_time: "Within a day",
    amenities: ["Lake Access", "Fireplace", "BBQ Area"],
    availability_calendar: "[Sample calendar data]",
    display_picture: "https://via.placeholder.com/500",
    coordinates: {
      latitude: 14.830795,
      longitude: 120.282779,
    },
  },
];
